name: ci

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4']
        dependencies: [highest]
        include:
          - php: '7.4'
            dependencies: lowest
          - php: '8.0'
            dependencies: highest
            composer-options: --ignore-platform-req=php
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: zip, pdo_sqlite, gd
          ini-values: pcov.directory=packages
          coverage: pcov
      - run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - uses: ramsey/composer-install@v1
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: ${{ matrix.composer-options }}
      - run: vendor/bin/phpunit --coverage-clover=clover.xml
      - uses: codecov/codecov-action@v1
