name: ci

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1']
        dependencies: [highest]
        include:
          - php: '7.4'
            dependencies: lowest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: zip, pdo_sqlite, gd
          ini-values: pcov.directory=packages
          coverage: pcov
      - run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}
      - run: vendor/bin/phpunit --coverage-clover=clover.xml
      - uses: codecov/codecov-action@v2
