name: monorepo

on:
  push:
    branches: [master]
    tags: ['*']

jobs:
  split:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.0']
        package:
          - { folder: basic-page-bundle, repository: RunroomBasicPageBundle }
          - { folder: ckeditor-sonata-media-bundle, repository: RunroomCkeditorSonataMediaBundle }
          - { folder: cookies-bundle, repository: RunroomCookiesBundle }
          - { folder: form-handler-bundle, repository: RunroomFormHandlerBundle }
          - { folder: redirection-bundle, repository: RunroomRedirectionBundle }
          - { folder: render-event-bundle, repository: RunroomRenderEventBundle }
          - { folder: seo-bundle, repository: RunroomSeoBundle }
          - { folder: sortable-behavior-bundle, repository: RunroomSortableBehaviorBundle }
          - { folder: testing, repository: testing }
          - { folder: translation-bundle, repository: RunroomTranslationBundle }
          - { folder: user-bundle, repository: RunroomUserBundle }
    steps:
      - uses: actions/checkout@v2
      - if: "!startsWith(github.ref, 'refs/tags/')"
        uses: symplify/github-action-monorepo-split@1.1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package-directory: packages/${{ matrix.package.folder }}
          split-repository-organization: runroom
          split-repository-name: ${{ matrix.package.repository }}
          user-name: Runroom
          user-email: software@runroom.com
          branch: master
      - if: "startsWith(github.ref, 'refs/tags/')"
        id: tag
        run: echo ::set-output name=CURRENT_TAG::${GITHUB_REF#refs/tags/}
      - if: "startsWith(github.ref, 'refs/tags/')"
        uses: symplify/github-action-monorepo-split@1.1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag: ${{ steps.tag.outputs.CURRENT_TAG }}
          package-directory: packages/${{ matrix.package.folder }}
          split-repository-organization: runroom
          split-repository-name: ${{ matrix.package.repository }}
          user-name: Runroom
          user-email: software@runroom.com
          branch: master
