name: qa

on: [push, pull_request]

jobs:
  php:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.3']
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.os }}-${{ matrix.php }}-composer
      - run: composer update --prefer-dist --no-progress --no-interaction --no-scripts
      - run: composer validate --strict
      - run: composer normalize-run -- --dry-run --diff
      - run: composer cs-fixer-run -- --dry-run --diff
      - run: composer phpstan
