name: qa

on:
  push:
    branches: [master]
  pull_request:

jobs:
  php:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4']
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: zip, pdo_sqlite, gd
          coverage: none
          tools: cs2pr
      - uses: ramsey/composer-install@v1
      - run: composer php-cs-fixer -- --dry-run --format=checkstyle | cs2pr
      - run: vendor/bin/phpunit
      - run: composer phpstan
      - run: composer psalm -- --threads=$(nproc) --output-format=github --shepherd
      - run: composer normalize-run -- --dry-run --diff
      - run: composer validate --strict
      - run: vendor/bin/monorepo-builder validate
