name: test

on:
  push:
    tags: ['*']

jobs:
  split:
    runs-on: ubuntu-latest
    steps:
      - if: "startsWith(github.ref, 'refs/tags/')"
        id: tag
        run: echo ::set-output name=CURRENT_TAG::${GITHUB_REF#refs/tags/}
      - if: "startsWith(github.ref, 'refs/tags/')"
        run: echo ${{ steps.tag.outputs.CURRENT_TAG }}
